services:
  exchange_rate:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    hostname: exchange_rate
    container_name: exchange_rate
    restart: always
    ports:
      - "49000:49000"
    volumes:
      - ./src/exchange_rate:/app/exchange_rate:ro
    env_file:
      - .env
    depends_on:
      - redis_cache

  redis_cache:
    image: redis:latest
    container_name: "redis_cache"
    hostname: "redis_cache"
    restart: always
    ports:
      - 6381:6379
volumes:
  redis:
    driver: local
